

export const API = 'API';
export const START_NETWORK = 'START_NETWORK';
export const END_NETWORK = 'END_NETWORK';
export const GENERIC_ERROR = 'GENERIC_ERROR';
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const ANSWER_QUESTION = 'ANSWER';
export const SET_ANSWER = 'SET_ANSWER';
export const SEW_CURRENT_INDEX = 'SEW_CURRENT_INDEX';
export const INCREMENT_CORRECT_COUNTER = 'INCREMENT_CORRECT_COUNTER';
export const RESET = 'RESET';